# -*- coding: utf-8 -*-
"""AI_Research_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1za2fxnfiUbhTLd2LVYnuUN9JOd8saMq3

##  **AI Research Assistant (RAG system)**

Installing
"""

!pip install -qU langchain langchain-community langchain-chroma langchain_groq chromadb gradio python-dotenv tiktoken

!pip install -U langchain-community sentence-transformers

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders.csv_loader import CSVLoader, Document
from langchain_classic.chains import RetrievalQA

"""Dataset loading"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("shree0910/arxiv-aiml-research-papers-20252026")

print("Path to dataset files:", path)

import pandas as pd
df = pd.read_csv("/kaggle/input/arxiv-aiml-research-papers-20252026/arxiv_ai_ml_papers.csv",encoding= "UTF-8")

df['text_for_embedding'] = df.apply(lambda row:
    f"Title: {row['title']}\n"
    f"Category: {row['primary_category']}\n"
    f"Abstract: {row['abstract']}\n"
    f"Source URL: {row['arxiv_url']}", axis=1)

df.head()

documents = []
for _, row in df.iterrows():
    doc = Document(page_content=row['text_for_embedding'])

   #metadata
    doc.metadata = {
        "url": row['arxiv_url'],
        "authors": row['authors'],
        "date": row['submitted_date'],
        "category": row['primary_category']
    }
    documents.append(doc)

"""splitting data & embedding"""

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1200, chunk_overlap=100)
docs = text_splitter.split_documents(documents)

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# vector DB
vectorstore = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory="./chroma_db")

#quick test for a query using similarity
query = "what is CNN"

docs_result = vectorstore.similarity_search(query, k=6)
# show results
for i, doc in enumerate(docs_result):
    print(f"--- Result {i+1} ---")
    print(f"Content: {doc.page_content}")
    print(f"Source URL: {doc.metadata['url']}\n")
    print("-" * 50)

from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

system_prompt = (
    "You are a professional AI Research Assistant. "
    "Any of your answers must be ONLY from the provided research abstracts in the context, each paper has it's abstract"
    "do not use external sources"
    "if there isn't information from the context, say there is not information provided regarding this topic"
    "\n\n"
    "Rules for Citations:"
    "1. For every piece of information you provide, cite the source using a number in brackets like [1], [2], etc."
    "2. These numbers must correspond to the order of the documents in the context."
    "3. lastly cite it at the end by it's title"

    "\n\n"
    "Context: {context}"
)
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        ("human", "{input}"),
    ]
)

import os
from google.colab import userdata
from langchain_groq import ChatGroq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

#model
llm = ChatGroq(
    model_name="llama-3.1-8b-instant",
    temperature=0.2
)

question_answer_chain = create_stuff_documents_chain(llm, prompt)

# retriever
rag_chain = create_retrieval_chain(vectorstore.as_retriever(), question_answer_chain)

import gradio as gr

def research_bot(question):
    try:

        response = rag_chain.invoke({"input": question})

        answer = response.get("answer", "No answer found.")


        sources_list = []
        docs = response.get("context", [])

        for i, doc in enumerate(docs, 1):
            url = doc.metadata.get('url', 'No Link')
            title = doc.metadata.get('title', 'Research Paper')
            sources_list.append(f"[{i}] {title}\n🔗 {url}")

        sources_final = "\n\n".join(sources_list) if sources_list else "No sources found."

        return answer, sources_final

    except Exception as e:
        return f"Error: {str(e)}", "Check Colab logs for details."

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 📚 AI Research Assistant")
    gr.Markdown("7700+ Latest ArXiv AI/ML Research Papers 2025–2026")

    with gr.Row():
        with gr.Column():
            input_text = gr.Textbox(label=" Ask your question", placeholder="Enter your question here...")
            btn = gr.Button("Search & Analyze", variant="primary")

        with gr.Column():
            output_answer = gr.Textbox(label="AI Analysis", interactive=False, lines=10)
            output_sources = gr.Markdown(label="Verified Sources & Links")

    btn.click(fn=research_bot, inputs=input_text, outputs=[output_answer, output_sources])

demo.launch(debug=True, share=True)